import streamlit as st
import pandas as pd
from databricks import sql
from st_aggrid import AgGrid, GridOptionsBuilder, GridUpdateMode

# ====================================================================
# CONFIGURATION
# ====================================================================
warehouse_id = "f50df4c3b0b8cb91"
DATABRICKS_SERVER = "adb-4151713458336319.19.azuredatabricks.net"
DATABRICKS_TOKEN = "dapi97bfcf4f2625d2d7d1c1982bcee6cf8d-3"

# ====================================================================
# HELPER FUNCTIONS
# ====================================================================
@st.cache_data
def sqlQuery(query: str) -> pd.DataFrame:
    with sql.connect(
        server_hostname=DATABRICKS_SERVER,
        http_path=f"/sql/1.0/warehouses/{warehouse_id}",
        access_token=DATABRICKS_TOKEN
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute(query)
            return cursor.fetchall_arrow().to_pandas()

# ====================================================================
# QUERY MENU
# ====================================================================
queries = [
    "001-CG1594 - WIP TAB",
    "002-CG1594 - PUBLISHED TAB",
    "2025 Workload",
    "Add Duplicate GMW to WIP",
    "Additional Documents",
    "All Active Standards",
    "Assign Multiple GMWs",
    "Body",
    "Body Changes",
    "CSV01 for Accuris - EXTERNAL RESTRICTED",
    "CSV02 for Accuris - HIGHLY RESTRICTED",
    "CSV03 for Accuris - EXTERNAL",
    "CSV04 for CG2569 - All",
    "CSV05 for CG2569 - Eng Stds Pub",
    "DNG",
    "Editables",
    "Fix Ownerships",
    "ILS: 001-WIP",
    "ILS: 002-OOPS - Ready to Publish",
    "ILS: 002-Ready to Publish",
    "ILS: 003-Submitted to Publisher",
    "ILS: 004-Published",
    "ILS: Batch Sheet - Additional Documents Folder",
    "ILS: Batch Sheet - ES Published Folder",
    "RECONCILE: Mark Published",
    "RECONCILE: Published Documents",
    "RECONCILE: TCIMM Notification",
    "Regionals",
    "Send to ILM folders-Remove from All Data",
    "SPCs",
    "Special Collection Honda Electrification (BEV)",
    "Special Collections - Monthly Publishing",
    "Update from CSV",
    "Year End Cleanup - Remove Duplicates",
    "Year End Cleanup - Remove Published",
    "Yearly ILM Review-Inactive",
    "Yearly ILM Review-LU/SUPER",
    "z0-Judy Tracking for Analysts - Status Report",
    "z0-Judy's Nagging List",
    "z1-Judy's Tracking List-WIP"
]


st.sidebar.title("Queries")
selection = None
for q in queries:
    if st.sidebar.button(q):
        selection = q
        break

# ====================================================================
# DISPLAY DATA
# ====================================================================
if selection:
    st.write(f"**Selected Query:** {selection}")
    
    sql_map = {
"001-CG1594 - WIP TAB": """SELECT 
    Record_ID, 
    WIP_Title, 
    Project, 
    Submit_Date, 
    Days_in_Process, 
    Key_Contact, 
    Analyst, 
    Action, 
    Local_Standards_Replaced, 
    Replaced_By, 
    Checked_for_Regulatory, 
    CG_Tracking_ID, 
    WIP_TAB, 
    PUBLISHED_TAB, 
    Ownership, 
    Final_Date, 
    ILS_Ready_to_Publish, 
    team_name_gdm, 
    Distribution_YYYYMM, 
    Distribution_YYYYMM_GDM, 
    Single_Point_Contact, 
    Num_Pages, 
    Team_Name, 
    Engineering_Standards_Status_GDM, 
    History, 
    Comments_to_Retain, 
    ILS_Comments, 
    ILS_Status, 
    Whats_the_Plan, 
    ILS_WIP, 
    Distribution_Type_Permitted_GDM, 
    Information_Security_Classification_GDM, 
    wl_2023_transfers, 
    Judy_Tracking_for_Analyst, 
    show_on_judy_tracking, 
    workload_2025_comments,
    KC_GMIN, 
    KC_Email
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE WIP_TAB = True
ORDER BY Record_ID, WIP_Title
""",
"002-CG1594 - PUBLISHED TAB": """select record_id,
wip_title,
project,
submit_date,
days_in_process,
key_contact,
analyst,
action,
local_standards_replaced,
replaced_by,
checked_for_regulatory,
distribution_year,
final_disposition_action,
final_date,
ils_published,
duplicates_for_published_tab_only,
process_step,
current_step_date,
num_pages,
ownership,
location,
days_in_step,
distribution_yyyymm_gdm,
wl_2023_transfers,
workload_2024_comments
from maxis_sandbox.engineering_standards.all_data_cleaned
where published_tab = true or duplicates_for_published_tab_only = true
order by record_id,final_date""",
    "2025 Workload": """select 
workload_2025_comments,
regional_elimination_planned_year,
team_name,
ownership,
single_point_contact,
key_contact,
date_editable_requested,
requestor_of_editable,
record_id,
hyperlink_latest_version_gdm,
name_gdm,
title_gdm,
engineering_standards_status_gdm,
native_language_title_gdm,
distribution_yyyymm_gdm,
distribution_type_permitted_gdm,
information_security_classification_gdm,
record_subtype_gdm,
standards_validation_area_gdm,
team_name_gdm,
stakeholders_gdm,
authors_gdm,
vpps_via_version,
vpps_via_level_1_gdm,
vpps_via_level_2_gdm,
vpps_via_level_3_gdm,
vpps_via_level_4_gdm,
standards_category_gdm,
standards_subcategory_gdm,
version_gdm,
user_comments_gdm,
description_gdm,
keyword_gdm,
alias_gdm,
region_gdm,
language_gdm,
electronic_collection_gdm,
regulatory_date_gdm,
regulatory_standards_gdm,
owner_gdm,
modifier_gdm,
source_system_gdm,
source_sys_load_date_gdm,
modifier_2_gdm,
object_id_gdm,
record_type_gdm,
global_process_area_gdm,
rim_category_gdm,
applicable_business_processes_gdm,
folder_gdm,
wip_tab,
published_tab,
analyst,
action,
project,
submit_date,
final_disposition_action,
final_date,
once,
wip_title,
do_not_include,
kc_gmin,
kc_email,
ils_ready_to_publish
from maxis_sandbox.engineering_standards.all_data_cleaned
WHERE Do_not_include = False AND Duplicates_for_Published_Tab_Only = False
ORDER BY Record_ID""",
"Add Duplicate GMW to WIP": """select 
record_id,
comments_to_retain,
wip_tab,
published_tab,
duplicates_for_published_tab_only,
analyst,
last_analyst,
total_num_pgs_pubd,
wip_title,
team_name,
single_point_contact,
key_contact,
ownership,
project,
action,
local_standards_replaced,
submit_date,
requestor_of_editable,
date_editable_requested,
record_id_gdm,
hyperlink_latest_version_gdm,
name_gdm,
title_gdm,
engineering_standards_status_gdm,
native_language_title_gdm,
distribution_yyyymm_gdm,
distribution_type_permitted_gdm,
information_security_classification_gdm,
record_subtype_gdm,
standards_validation_area_gdm,
team_name_gdm,
stakeholders_gdm,
authors_gdm,
vpps_via_version,
vpps_via_level_1_gdm,
vpps_via_level_2_gdm,
vpps_via_level_3_gdm,
vpps_via_level_4_gdm,
standards_category_gdm,
standards_subcategory_gdm,
version_gdm,
user_comments_gdm,
description_gdm,
keyword_gdm,
alias_gdm,
region_gdm,
language_gdm,
electronic_collection_gdm,
regulatory_date_gdm,
regulatory_standards_gdm,
record_id_issue_date_gdm,
owner_gdm,
content_date_gdm,
modifier_gdm,
modified_gdm,
source_system_gdm,
source_sys_load_date_gdm,
modifier_2_gdm,
object_id_gdm,
record_type_gdm,
global_process_area_gdm,
rim_category_gdm,
applicable_business_processes_gdm,
folder_gdm,
distribution_year,
distribution_yyyymm,
team_name_on_cg746,
days_in_process,
checked_for_regulatory,
cg_tracking_id,
num_pages,
final_disposition_action,
final_date,
pending_gmw_for_cg,
process_step,
location,
current_step_date,
days_in_step,
history,
ils_wip,
ils_ready_to_publish,
ils_submitted_to_publisher,
ils_published,
ils_action,
action_2,
replaced_by,
ils_submit_date,
ils_status,
ils_comments,
priority,
`sort`,
project_998_list,
project_998_closed,
rep_998_comments,
rep_998_action,
rep_998_replaced_by,
regional_elimination_planned_year,
area_998,
update_csv,
temp_check_box,
confirmed_no_supplements,
materials_998s_2022,
whats_the_plan,
honda_autonomous_special_collection,
honda_autonomous_added,
honda_autonomous_confirmed,
honda_autonomous_most_current_version_approved,
honda_autonomous_audit_found,
honda_electrification_bev_special_collection,
honda_electrification_bev_added,
honda_electrification_bev_confirmed,
honda_electrification_bev_most_current_version_approved,
honda_electrification_bev_audit_found,
cruise_automation_special_collection,
cruise_added,
cruise_confirmed,
cruise_most_current_version_approved,
cruise_audit_found,
workload_2023_comments,
comments_cruise_automation_special_collection,
comments_honda_autonomous_special_collection,
comments_honda_electrification_bev_special_collection,
sco_message_20221202,
assign_2023,
etl,
next_follow_up,
honda_affordable_electric_vehicle_aev_special_collection,
honda_affordable_electric_vehicle_aev_added,
honda_affordable_electric_vehicle_aev_confirmed,
comments_honda_aev,
country,
referenced_records,
personal_information_included,
non_disclosure_agreement_applies,
export_control_number,
source_rec_id,
source_rec_info,
source_rec_url,
format,
follow_up_comments,
record_status,
wl_2023_transfers,
update_csv_2,
wl_2023_transfer_status,
record_id_ihs,
ihs_audit_comments,
show_on_judy_tracking,
judy_tracking_for_analyst,
analyst_tracking_for,
assign_2024,
do_not_include,
workload_2024_comments,
once,
powertrain_comments,
once_comments,
distribution_date,
workload_2025_comments
from maxis_sandbox.engineering_standards.all_data_cleaned
order by record_id

""",
"Additional Documents": """ SELECT
  Record_ID,
  WIP_Title,
  Team_Name,
  Key_Contact,
  Ownership,
  Single_Point_Contact,
  Distribution_YYYYMM,
  WIP_TAB,
  PUBLISHED_TAB,
  Engineering_Standards_Status_GDM,
  Distribution_Type_Permitted_GDM,
  Analyst,
  Distribution_YYYYMM_GDM,
  Comments_to_Retain,
  team_name_gdm,
  Folder_GDM,
  hyperlink_latest_version_gdm,
  KC_GMIN,
  KC_Email,
  Last_Analyst,
  Final_Disposition_Action,
  Final_Date
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE Folder_GDM = 'Additional Documents'
ORDER BY Record_ID;

""",
"All Active Standards": """SELECT 
    record_id,
    wip_title,
    team_name,
    key_contact,
    ownership,
    single_point_contact,
    distribution_yyyymm,
    wip_tab,
    published_tab,
    engineering_standards_status_gdm,
    distribution_type_permitted_gdm,
    analyst,
    distribution_yyyymm_gdm,
    comments_to_retain,
    team_name_gdm,
    folder_gdm,
    hyperlink_latest_version_gdm,
    kc_gmin,
    kc_email,
    last_analyst,
    final_disposition_action,
    final_date
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE engineering_standards_status_gdm = 'Active'
ORDER BY record_id""",
    "Assign Multiple GMWs": """SELECT 
    record_id,
    wip_title,
    team_name,
    key_contact,
    ownership,
    single_point_contact,
    distribution_yyyymm,
    wip_tab,
    published_tab,
    engineering_standards_status_gdm,
    distribution_type_permitted_gdm,
    analyst,
    distribution_yyyymm_gdm,
    comments_to_retain,
    team_name_gdm,
    folder_gdm,
    hyperlink_latest_version_gdm,
    kc_gmin,
    kc_email,
    last_analyst,
    project,
    rfi_for_collaboration,
    dng,
    ils_wip,
    action,
    submit_date
FROM maxis_sandbox.engineering_standards.all_data_cleaned
ORDER BY record_id""",
"Body":"""SELECT
  Record_ID,
  WIP_Title,
  Team_Name,
  Key_Contact,
  Ownership,
  Single_Point_Contact,
  Distribution_YYYYMM,
  WIP_TAB,
  PUBLISHED_TAB,
  Engineering_Standards_Status_GDM,
  Distribution_Type_Permitted_GDM,
  Analyst,
  Distribution_YYYYMM_GDM,
  Comments_to_Retain,
  team_name_gdm,
  Folder_GDM,
  hyperlink_latest_version_gdm,
  KC_GMIN,
  KC_Email,
  Last_Analyst,
  Final_Disposition_Action,
  Final_Date,
  Once,
  Duplicates_for_Published_Tab_Only
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE Once = True AND Duplicates_for_Published_Tab_Only = False
ORDER BY Record_ID;""",
"Body Changes":""" SELECT
  Record_ID,
  WIP_Title,
  Team_Name,
  Key_Contact,
  Ownership,
  Single_Point_Contact,
  Distribution_YYYYMM,
  WIP_TAB,
  PUBLISHED_TAB,
  Engineering_Standards_Status_GDM,
  Distribution_Type_Permitted_GDM,
  Analyst,
  Distribution_YYYYMM_GDM,
  Comments_to_Retain,
team_name_gdm,
  Folder_GDM,
 hyperlink_latest_version_gdm,
  KC_GMIN,
  KC_Email,
  Last_Analyst,
  Final_Disposition_Action,
  Final_Date,
  Duplicates_for_Published_Tab_Only
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE Record_ID IN (
  'GMW14139', 'GMW14261', 'GMW14268', 'GMW14277', 'GMW14279', 'GMW14280', 
  'GMW14281', 'GMW14282', 'GMW14283', 'GMW14284', 'GMW14285', 'GMW14319', 
  'GMW14322', 'GMW14323', 'GMW14325', 'GMW14718', 'GMW14780', 'GMW15011', 
  'GMW15018', 'GMW15078', 'GMW15079', 'GMW15090', 'GMW15259', 'GMW15364', 
  'GMW15465', 'GMW15622', 'GMW15659', 'GMW15661', 'GMW15662', 'GMW15673', 
  'GMW15675', 'GMW15701', 'GMW15704', 'GMW15705', 'GMW15753', 'GMW15754', 
  'GMW15773', 'GMW15775', 'GMW15789', 'GMW15799', 'GMW15804', 'GMW15810', 
  'GMW15819', 'GMW15835', 'GMW15838', 'GMW15845', 'GMW15922', 'GMW15936', 
  'GMW15942', 'GMW15943', 'GMW15955', 'GMW15966', 'GMW15996', 'GMW16001', 
  'GMW16115', 'GMW16136', 'GMW16137', 'GMW16142', 'GMW16143', 'GMW16151', 
  'GMW16154', 'GMW16157', 'GMW16158', 'GMW16159', 'GMW16162', 'GMW16224', 
  'GMW16281', 'GMW16282', 'GMW16393', 'GMW16403', 'GMW16412', 'GMW16421', 
  'GMW16423', 'GMW16500', 'GMW16571', 'GMW16583', 'GMW16591', 'GMW16598', 
  'GMW16599', 'GMW16602', 'GMW16604', 'GMW16608', 'GMW16621', 'GMW16642', 
  'GMW16643', 'GMW16646', 'GMW16651', 'GMW16661', 'GMW16679', 'GMW16689', 
  'GMW16754', 'GMW16809', 'GMW16812', 'GMW16889', 'GMW16932', 'GMW16950', 
  'GMW16951', 'GMW16952', 'GMW16957', 'GMW17039', 'GMW17053', 'GMW17054', 
  'GMW17058', 'GMW17069', 'GMW17074', 'GMW17075', 'GMW17077', 'GMW17146', 
  'GMW17181', 'GMW17191', 'GMW17210', 'GMW17213', 'GMW17275', 'GMW17368', 
  'GMW17383', 'GMW17615', 'GMW17625', 'GMW17655', 'GMW17738', 'GMW17775', 
  'GMW17776', 'GMW17880', 'GMW17919', 'GMW17920', 'GMW17927', 'GMW17943', 
  'GMW17944', 'GMW17946', 'GMW17963', 'GMW17988', 'GMW18008', 'GMW18070', 
  'GMW18073', 'GMW18078', 'GMW18080', 'GMW18093', 'GMW18103', 'GMW18132', 
  'GMW18145', 'GMW18156', 'GMW18162', 'GMW18164', 'GMW18209', 'GMW18220', 
  'GMW18250', 'GMW18255', 'GMW18264', 'GMW18275', 'GMW18301', 'GMW18396', 
  'GMW18401', 'GMW18402', 'GMW18411', 'GMW18412', 'GMW18434', 'GMW18468', 
  'GMW18491', 'GMW18545', 'GMW18569', 'GMW18587', 'GMW18588', 'GMW18589', 
  'GMW18606', 'GMW18661', 'GMW18665', 'GMW18671', 'GMW18696', 'GMW18697', 
  'GMW18743', 'GMW18753', 'GMW18765', 'GMW18784', 'GMW18789', 'GMW18798', 
  'GMW18799', 'GMW3037', 'GMW3040', 'GMW3043', 'GMW3046', 'GMW3049', 
  'GMW3052', 'GMW3055', 'GMW3058', 'GMW3067', 'GMW3070', 'GMW3076', 
  'GMW3079', 'GMW3136', 'GMW7022', 'GMW7023', 'GMW8697'
)
AND Duplicates_for_Published_Tab_Only = False
ORDER BY Record_ID; """,
"CSV01 for Accuris - EXTERNAL RESTRICTED": """  SELECT
  Record_ID,
  Key_Contact,
  Team_Name,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Update_CSV,
  Duplicates_for_Published_Tab_Only,
  KC_GMIN,
  KC_Email,
  Final_Date
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE hyperlink_latest_version_gdm IS NOT NULL
  AND Engineering_Standards_Status_GDM = 'Active'
  AND Distribution_Type_Permitted_GDM = 'External Restricted'
ORDER BY Record_ID, Record_ID_GDM; """,
"CSV02 for Accuris - HIGHLY RESTRICTED" : """  SELECT
  Record_ID,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Update_CSV,
  Duplicates_for_Published_Tab_Only,
  Key_Contact,
  ETL,
  Final_Date,
  KC_GMIN,
  KC_Email
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE hyperlink_latest_version_gdm IS NOT NULL
  AND Engineering_Standards_Status_GDM = 'Active'
  AND Distribution_Type_Permitted_GDM = 'External Highly Restricted'
ORDER BY Record_ID, Record_ID_GDM
 """,
 "CSV03 for Accuris - EXTERNAL" : """ 
SELECT
  Record_ID,
  Key_Contact,
  Team_Name,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Update_CSV,
  Duplicates_for_Published_Tab_Only,
  KC_GMIN,
  KC_Email,
  Distribution_YYYYMM
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE hyperlink_latest_version_gdm IS NOT NULL
  AND Engineering_Standards_Status_GDM = 'Active'
  AND Distribution_Type_Permitted_GDM = 'External'
ORDER BY Record_ID, Record_ID_GDM
  """,
"CSV04 for CG2569 - All" : """ 
SELECT
  Record_ID,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Update_CSV,
  Duplicates_for_Published_Tab_Only,
  Team_Name,
  Single_Point_Contact,
  Key_Contact,
  Comments_to_Retain,
  WIP_TAB,
  WIP_Title,
  Analyst,
  Ownership,
  VPPS_VIA_Version,
  Country,
  Referenced_Records,
  Personal_Information_Included,
  Non_Disclosure_Agreement_Applies,
  Export_Control_Number,
  Source_Rec_ID,
  Source_Rec_Info,
  Source_Rec_URL,
  Record_Status,
  Distribution_Date,
  Format,
  Project,
  KC_GMIN,
  KC_Email
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE hyperlink_latest_version_gdm IS NOT NULL
ORDER BY Record_ID, Record_ID_GDM
""",
"CSV05 for CG2569 - Eng Stds Pub" : """ SELECT
  Record_ID,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Update_CSV,
  Duplicates_for_Published_Tab_Only,
  Team_Name,
  Single_Point_Contact,
  Key_Contact,
  Comments_to_Retain,
  WIP_TAB,
  WIP_Title,
  Analyst,
  History,
  Ownership,
  VPPS_VIA_Version,
  Country,
  Referenced_Records,
  Personal_Information_Included,
  Non_Disclosure_Agreement_Applies,
  Export_Control_Number,
  Source_Rec_ID,
  Source_Rec_Info,
  Source_Rec_URL,
  Record_Status,
  Distribution_Date,
  Format,
  Project,
  Final_Date
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Record_ID_GDM IS NOT NULL
  AND hyperlink_latest_version_gdm IS NOT NULL
  AND Folder_GDM = 'Engineering Standards Published'
ORDER BY Record_ID, Record_ID_GDM """,
"DNG" : """
SELECT
  Record_ID,
  Final_Date,
  WIP_Title,
  Team_Name,
  Key_Contact,
  Ownership,
  Single_Point_Contact,
  Distribution_YYYYMM,
  WIP_TAB,
  PUBLISHED_TAB,
  Engineering_Standards_Status_GDM,
  Distribution_Type_Permitted_GDM,
  Analyst,
  Distribution_YYYYMM_GDM,
  team_name_gdm,
  Folder_GDM,
  hyperlink_latest_version_gdm,
  KC_GMIN,
  KC_Email,
  DNG,
  Num_CGs_in_DNG_Document,
  DNG_Link,
  Version_GDM
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE DNG = True
ORDER BY Record_ID
 """,
 "Editables": """ SELECT
  Record_ID,
  WIP_Title,
  Key_Contact,
  Team_Name,
  Ownership,
  WIP_TAB,
  Requestor_of_Editable,
  Date_Editable_Requested,
  Distribution_YYYYMM_GDM,
  Comments_to_Retain,
  PUBLISHED_TAB,
  Final_Date
FROM maxis_sandbox.engineering_standards.all_data_cleaned""",
"Fix Ownerships": """ SELECT
  Record_ID,
  WIP_Title,
  Team_Name,
  Key_Contact,
  Ownership,
  Single_Point_Contact,
  Distribution_YYYYMM,
  WIP_TAB,
  PUBLISHED_TAB,
  Engineering_Standards_Status_GDM,
  Distribution_Type_Permitted_GDM,
  Analyst,
  Distribution_YYYYMM_GDM,
  Comments_to_Retain
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Ownership IN (
    'Powertrain-Electrification Verification or Research and Development - Battery Cell Systems Research',
    'TIPIE-Fuels',
    'Not Powertrain-Controls (not Powertrain-Electrification Verification)',
    'Materials-Ferrous (incl. Sheet Metal)',
    'Body-Structures',
    'Mfg Eng-Paint & Seal Materials'
  )
  AND Engineering_Standards_Status_GDM = 'Active'""",
"ILS: 001-WIP": """ SELECT
  Record_ID,
  ILS_Action,
  Action_2,
  Action,
  Replaced_by,
  ILS_Submit_Date,
  key_contact,
  Team_Name,
  Analyst,
  ILS_WIP,
  ILS_Ready_to_Publish,
  total_num_pgs_pubd,
  Submit_Date,
  ILS_Status,
  ILS_Comments,
  Confirmed_No_Supplements,
  Description_GDM,
  Project,
  Standards_Validation_Area_GDM,
  Follow_Up_Comments,
  Next_Follow_Up,
  Information_Security_Classification_GDM,
  Distribution_Type_Permitted_GDM,
  WIP_TAB
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  ILS_WIP = True AND ILS_Ready_to_Publish = False
ORDER BY Record_ID, ILS_Action, Action_2""",
"ILS: 002-OOPS - Ready to Publish":"""SELECT
  Action,
  ILS_Action,
  Action_2,
  Standards_Validation_Area_GDM,
  Record_SubType_GDM,
  Replaced_by,
  Record_ID,
  ILS_Submit_Date,
  key_contact,
  Team_Name,
  Analyst,
  ILS_Comments,
  ILS_Ready_to_Publish,
  Distribution_YYYYMM,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  ILS_Submitted_to_Publisher,
  ILS_Status,
  total_num_pgs_pubd,
  Submit_Date,
  Confirmed_No_Supplements
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  ILS_Ready_to_Publish = True
  AND Confirmed_No_Supplements = False
ORDER BY
  ILS_Action,
  Action_2,
  Standards_Validation_Area_GDM,
  Record_SubType_GDM,
  Record_ID""",
  "ILS: 002-Ready to Publish" : """ SELECT
  Action,
  ILS_Action,
  Action_2,
  Standards_Validation_Area_GDM,
  Record_SubType_GDM,
  Replaced_by,
  Record_ID,
  ILS_Submit_Date,
  key_contact,
  Team_Name,
  Analyst,
  ILS_Comments,
  ILS_Ready_to_Publish,
  Distribution_YYYYMM,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  ILS_Submitted_to_Publisher,
  ILS_Status,
  total_num_pgs_pubd,
  Submit_Date,
  Confirmed_No_Supplements,
  VPPS_VIA_Version,
  Country,
  Referenced_Records,
  ILS_WIP
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  ILS_Ready_to_Publish = True
  AND Confirmed_No_Supplements = True
ORDER BY
  ILS_Action,
  Action_2,
  Standards_Validation_Area_GDM,
  Record_ID""",
  "ILS: 003-Submitted to Publisher": """ SELECT
  Action,
  ILS_Action,
  Action_2,
  Replaced_by,
  Record_ID,
  ILS_Submit_Date,
  key_contact,
  Team_Name,
  Analyst,
  ILS_Comments,
  ILS_Submitted_to_Publisher,
  Distribution_YYYYMM,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  ILS_Published,
  WIP_TAB,
  PUBLISHED_TAB,
  ILS_Status,
  Final_Date,
  Final_Disposition_Action,
  Process_Step,
  Current_Step_Date,
 total_num_pgs_pubd
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  ILS_Submitted_to_Publisher = True
ORDER BY
  ILS_Action,
  Action_2,
  Record_ID""",
    "ILS: 004-Published": """SELECT
  Record_ID,
  Action,
  ILS_Action,
  Action_2,
  Replaced_by,
  ILS_Submit_Date,
  key_contact,
  Team_Name,
  Analyst,
  ILS_Comments,
  ILS_Status,
  Record_ID_GDM,
hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Final_Disposition_Action,
  Final_Date,
  ILS_Published,
  PUBLISHED_TAB,
 total_num_pgs_pubd,
  wl_2023_transfer_status,
  wl_2023_transfers
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  ILS_Published = True
ORDER BY
  Record_ID """,
    "ILS: Batch Sheet - Additional Documents Folder": """ SELECT
  ILS_Action,
  Action_2,
  Title_GDM,
  Native_Language_Title_GDM,
  Record_SubType_GDM,
  Content_Date_GDM,
  VPPS_VIA_Version,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Country,
  Regulatory_Standards_GDM,
  Regulatory_Date_GDM,
  Team_Name,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Applicable_Business_Processes_GDM,
  Stakeholders_GDM,
  Electronic_Collection_GDM,
  Engineering_Standards_Status_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Standards_Validation_Area_GDM,
  Record_ID_GDM,
  Record_ID_Issue_Date_GDM,
  Referenced_Records,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Authors_GDM,
  Region_GDM,
  Language_GDM,
  Information_Security_Classification_GDM,
  Personal_Information_Included,
  Non_Disclosure_Agreement_Applies,
  Export_Control_Number,
  User_Comments_GDM,
  Source_Rec_ID,
  Source_Rec_Info,
  Source_Rec_URL,
  Folder_GDM,
  ILS_Ready_to_Publish
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Record_ID_GDM IS NOT NULL
  AND Record_ID_GDM <> '000-Don''t Type here - Use Search'
  AND Folder_GDM = 'Additional Documents'
  AND ILS_Ready_to_Publish = True
ORDER BY ILS_Action, Action_2, Record_ID_GDM """,
    "ILS: Batch Sheet - ES Published Folder": """ SELECT
  ILS_Action,
  Action_2,
  Title_GDM,
  Native_Language_Title_GDM,
  Record_SubType_GDM,
  Content_Date_GDM,
  VPPS_VIA_Version,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Country,
  Regulatory_Standards_GDM,
  Regulatory_Date_GDM,
  Team_Name,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Applicable_Business_Processes_GDM,
  Stakeholders_GDM,
  Electronic_Collection_GDM,
  Engineering_Standards_Status_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Standards_Validation_Area_GDM,
  Record_ID_GDM,
  Record_ID_Issue_Date_GDM,
  Referenced_Records,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Authors_GDM,
  Region_GDM,
  Language_GDM,
  Information_Security_Classification_GDM,
  Personal_Information_Included,
  Non_Disclosure_Agreement_Applies,
  Export_Control_Number,
  User_Comments_GDM,
  Source_Rec_ID,
  Source_Rec_Info,
  Source_Rec_URL,
  Folder_GDM,
  ILS_Ready_to_Publish,
  team_name_gdm
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Record_ID_GDM IS NOT NULL
  AND Record_ID_GDM <> '000-Don''t Type here - Use Search'
  AND Folder_GDM = 'Engineering Standards Published'
  AND ILS_Ready_to_Publish = True
ORDER BY ILS_Action, Action_2, Record_ID_GDM""",
"RECONCILE: Mark Published" :"""SELECT
  Record_ID,
  WIP_TAB,
  PUBLISHED_TAB,
  Final_Disposition_Action,
  Final_Date,
  Update_CSV,
  Distribution_Year,
  ILS_Published,
  ILS_Submitted_to_Publisher,
  hyperlink_latest_version_gdm,
  Record_SubType_GDM,
  DNG,
  RFI_for_Collaboration,
  DNG_Link
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE WIP_TAB = True
ORDER BY Record_ID""",
    "RECONCILE: Published Documents": """ SELECT
  Analyst,
  Record_ID,
  Final_Date,
  Final_Disposition_Action,
  Honda_Autonomous_Special_Collection,
  Honda_Electrification_BEV_Special_Collection,
  Cruise_Automation_Special_Collection,
  Distribution_Type_Permitted_GDM,
  WIP_Title,
  ILS_WIP,
  ILS_Ready_to_Publish,
  ILS_Submitted_to_Publisher,
  hyperlink_latest_version_gdm,
  Record_SubType_GDM,
  Action,
  workload_2025_comments
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Final_Date = '26-Jun-25'
ORDER BY Analyst, Record_ID""",
    "RECONCILE: TCIMM Notification": """ SELECT
  Record_ID,
hyperlink_latest_version_gdm,
  Action,
  Final_Date,
  WIP_Title,
  Record_SubType_GDM
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Final_Disposition_Action = 'Published'
ORDER BY Record_ID""",
    "Regionals": """ SELECT
  Record_ID,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Update_CSV,
  Team_Name,
  Single_Point_Contact,
  Key_Contact,
  Comments_to_Retain,
  WIP_TAB,
  WIP_Title,
  Analyst,
  History,
  Regional_Elimination_Planned_Year,
  Project,
  ILS_Submitted_to_Publisher,
  KC_GMIN,
  KC_Email
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
hyperlink_latest_version_gdm IS NOT NULL
  AND Engineering_Standards_Status_GDM = 'Active'
  AND Standards_Validation_Area_GDM <> 'GM Worldwide'
  AND ILS_Submitted_to_Publisher = False
  AND Duplicates_for_Published_Tab_Only = False
  AND PUBLISHED_TAB = False
ORDER BY Record_ID, Record_ID_GDM """,
    "Send to ILM folders-Remove from All Data": """ SELECT
  Record_ID_GDM,
  Record_ID,
  WIP_Title,
  Team_Name,
  Single_Point_Contact,
  Key_Contact,
  Ownership,
  Distribution_Year,
  Distribution_YYYYMM,
  Comments_to_Retain,
  Project,
  Submit_Date,
  Action,
  Local_Standards_Replaced,
  Analyst,
  Final_Disposition_Action,
  Final_Date,
  History,
hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
team_name_gdm
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM
FROM maxis_sandbox.engineering_standards.all_data_cleaned""",
    "SPCs": """ SELECT
  team_name,
  Ownership,
  Single_Point_Contact,
  GFL_Name,
  GFL_Function,
  Owning_Leader,
  Technical_Leader
FROM maxis_sandbox.engineering_standards.spcs_with_ownership
ORDER BY Team_Name, Ownership""",
    "Special Collection Honda Electrification (BEV)": """  SELECT
  Honda_Electrification_BEV_Special_Collection,
  Record_ID_GDM,
  Key_Contact,
  WIP_Title,
  Team_Name,
  WIP_TAB,
  Analyst,
  Engineering_Standards_Status_GDM,
  Distribution_Type_Permitted_GDM,
  Distribution_YYYYMM_GDM,
  Comments_Honda_Electrification_BEV_Special_Collection,
  Honda_Electrification_BEV_Most_Current_Version_Approved,
  Description_GDM
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Honda_Electrification_BEV_Special_Collection = True
ORDER BY Record_ID_GDM""",
    "Special Collections - Monthly Publishing": """SELECT
  Distribution_YYYYMM_GDM,
  Record_ID,
  Final_Date,
  Final_Disposition_Action,
  Honda_Electrification_BEV_Special_Collection,
  Distribution_Type_Permitted_GDM,
  WIP_Title,
  Replaced_by
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Distribution_YYYYMM_GDM = '202505'
  AND Honda_Electrification_BEV_Special_Collection = True
ORDER BY Record_ID""",
    "Update from CSV": """ SELECT
  Record_ID,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  VPPS_VIA_Version,
  Country,
  Referenced_Records,
  Personal_Information_Included,
  Non_Disclosure_Agreement_Applies,
  Export_Control_Number,
  Source_Rec_ID,
  Source_Rec_Info,
  Record_Status,
  Source_Rec_URL,
  Format,
  Update_CSV,
  Distribution_Year
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  update_csv = True
ORDER BY Record_ID, Record_ID_GDM""",
    "Year End Cleanup - Remove Duplicates": """ SELECT
  Record_ID,
  WIP_Title,
  Project,
  Submit_Date,
  Days_in_Process,
  Key_Contact,
  Analyst,
  Action,
  Local_Standards_Replaced,
  Replaced_by,
  Checked_for_Regulatory,
  Distribution_Year,
  Final_Disposition_Action,
  Final_Date,
  ILS_Published,
  Duplicates_for_Published_Tab_Only,
  Process_Step,
  Current_Step_Date,
  Num_Pages,
  Ownership,
  Location,
  Days_in_Step
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Duplicates_for_Published_Tab_Only = True
ORDER BY Record_ID, WIP_Title""",
    "Year End Cleanup - Remove Published": """ SELECT
  Project,
  Submit_Date,
  Days_in_Process,
  Analyst,
  Action,
  Local_Standards_Replaced,
  Replaced_by,
  Checked_for_Regulatory,
  Final_Disposition_Action,
  Final_Date,
  ILS_Published,
  Process_Step,
  Current_Step_Date,
  Location,
  Days_in_Step,
  Last_Analyst,
  PUBLISHED_TAB,
  ILS_Action,
  Action_2,
  ILS_Submit_Date,
  ILS_Status,
  ILS_Comments
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  PUBLISHED_TAB = True""",
    "Yearly ILM Review-Inactive": """ SELECT
  Record_ID,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Update_CSV,
  Duplicates_for_Published_Tab_Only,
  Team_Name,
  Single_Point_Contact,
  Key_Contact,
  Comments_to_Retain,
  WIP_TAB,
  WIP_Title,
  Analyst,
  Project,
  Submit_Date,
  Days_in_Process,
  Action,
  Local_Standards_Replaced,
  Replaced_by,
  Ownership,
  Process_Step,
  Location,
  Current_Step_Date,
  Num_Pages,
  History,
  Days_in_Step
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  hyperlink_latest_version_gdm IS NOT NULL
  AND Distribution_YYYYMM_GDM < '197501'
  AND (
    Engineering_Standards_Status_GDM = 'Inactive'
    OR Engineering_Standards_Status_GDM = 'Cancelled'
  )
ORDER BY Record_ID, Record_ID_GDM """,
    "Yearly ILM Review-LU/SUPER": """ SELECT
  Record_ID,
  Record_ID_GDM,
  hyperlink_latest_version_gdm,
  Name_GDM,
  Title_GDM,
  Engineering_Standards_Status_GDM,
  Native_Language_Title_GDM,
  Distribution_YYYYMM_GDM,
  Distribution_Type_Permitted_GDM,
  Information_Security_Classification_GDM,
  Record_SubType_GDM,
  Standards_Validation_Area_GDM,
  team_name_gdm,
  Stakeholders_GDM,
  Authors_GDM,
  VPPS_VIA_Level_1_GDM,
  VPPS_VIA_Level_2_GDM,
  VPPS_VIA_Level_3_GDM,
  VPPS_VIA_Level_4_GDM,
  Standards_Category_GDM,
  Standards_Subcategory_GDM,
  Version_GDM,
  User_Comments_GDM,
  Description_GDM,
  Keyword_GDM,
  Alias_GDM,
  Region_GDM,
  Language_GDM,
  Electronic_Collection_GDM,
  Regulatory_Date_GDM,
  Regulatory_Standards_GDM,
  Record_ID_Issue_Date_GDM,
  Owner_GDM,
  Content_Date_GDM,
  Modifier_GDM,
  Modified_GDM,
  Source_System_GDM,
  Source_Sys_Load_Date_GDM,
  Modifier_2_GDM,
  Object_ID_GDM,
  Record_Type_GDM,
  Global_Process_Area_GDM,
  RIM_Category_GDM,
  Applicable_Business_Processes_GDM,
  Folder_GDM,
  Update_CSV,
  Duplicates_for_Published_Tab_Only,
  Team_Name,
  Single_Point_Contact,
  Key_Contact,
  Comments_to_Retain,
  WIP_TAB,
  WIP_Title,
  Analyst,
  Project,
  Submit_Date,
  Days_in_Process,
  Action,
  Local_Standards_Replaced,
  Replaced_by,
  Ownership,
  Process_Step,
  Location,
  Current_Step_Date,
  Num_Pages,
  History,
  Days_in_Step
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  hyperlink_latest_version_gdm IS NOT NULL
  AND Distribution_YYYYMM_GDM < '200501'
  AND (
    Engineering_Standards_Status_GDM = 'Limited Use'
    OR Engineering_Standards_Status_GDM = 'Supercede'
    OR Engineering_Standards_Status_GDM = 'Superceded'
  )
ORDER BY Record_ID, Record_ID_GDM""",
    "z0-Judy Tracking for Analysts - Status Report": """ SELECT
  Record_ID,
  WIP_Title,
  Project,
  Submit_Date,
  Days_in_Process,
  Key_Contact,
  Next_Follow_Up,
  Analyst,
  Action,
  Local_Standards_Replaced,
  Replaced_by,
  Ownership,
  Process_Step,
  Location,
  Current_Step_Date,
  Days_in_Step,
  History,
  WIP_TAB,
  PUBLISHED_TAB,
  ILS_Ready_to_Publish,
  Num_Pages,
  Team_Name,
  Engineering_Standards_Status_GDM,
  Comments_to_Retain,
  ILS_Comments,
  ILS_Status,
  Follow_Up_Comments,
  ILS_WIP,
  Folder_GDM,
  Information_Security_Classification_GDM,
  Distribution_Type_Permitted_GDM,
  Record_ID_Issue_Date_GDM,
  wl_2023_transfer_status,
  Analyst_Tracking_for,
  Judy_Tracking_for_Analyst,
  Final_Disposition_Action,
  show_on_judy_tracking,
  Distribution_YYYYMM_GDM
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Judy_Tracking_for_Analyst = True
ORDER BY Record_ID, WIP_Title""",
    "z0-Judy's Nagging List": """ SELECT
  Record_ID,
  WIP_Title,
  Project,
  Submit_Date,
  Days_in_Process,
  Key_Contact,
  Next_Follow_Up,
  Analyst,
  WIP_TAB,
  show_on_judy_tracking,
  Action,
  Local_Standards_Replaced,
  Replaced_by,
  Ownership,
  Process_Step,
  Location,
  Current_Step_Date,
  Days_in_Step,
  History,
  PUBLISHED_TAB,
  ILS_Ready_to_Publish,
  Num_Pages,
  Team_Name,
  Engineering_Standards_Status_GDM,
  Comments_to_Retain,
  ILS_Comments,
  ILS_Status,
  Follow_Up_Comments,
  ILS_WIP,
  Folder_GDM,
  Information_Security_Classification_GDM,
  Distribution_Type_Permitted_GDM,
  Record_ID_Issue_Date_GDM,
  Analyst_Tracking_for,
  Regional_Elimination_Planned_Year
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  (
    Analyst = 'Judy Brombach'
    AND WIP_TAB = True
  )
  OR show_on_judy_tracking = True
ORDER BY Record_ID, WIP_Title""",
    "z1-Judy's Tracking List-WIP": """ SELECT
  Record_ID,
  WIP_Title,
  Project,
  Submit_Date,
  Days_in_Process,
  Key_Contact,
  Next_Follow_Up,
  Analyst,
  WIP_TAB,
  show_on_judy_tracking,
  Action,
  Local_Standards_Replaced,
  Replaced_by,
  Ownership,
  Process_Step,
  Location,
  Current_Step_Date,
  Days_in_Step,
  History,
  PUBLISHED_TAB,
  ILS_Ready_to_Publish,
  Num_Pages,
  Team_Name,
  Engineering_Standards_Status_GDM,
  Comments_to_Retain,
  ILS_Comments,
  ILS_Status,
  Follow_Up_Comments,
  ILS_WIP,
  Folder_GDM,
  Information_Security_Classification_GDM,
  Distribution_Type_Permitted_GDM,
  Record_ID_Issue_Date_GDM,
  Analyst_Tracking_for,
  Regional_Elimination_Planned_Year
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE
  Analyst = 'Judy Brombach'
  AND WIP_TAB = True
ORDER BY Record_ID, WIP_Title"""

}

    
    query_string = sql_map.get(selection, f"SELECT * FROM {selection.replace(' ', '_')} LIMIT 100")
    df = sqlQuery(query_string)
    
    gb = GridOptionsBuilder.from_dataframe(df)
    gb.configure_pagination()
    gb.configure_default_column(editable=True)
    grid_options = gb.build()
    
    AgGrid(df, gridOptions=grid_options, update_mode=GridUpdateMode.NO_UPDATE)
