import streamlit as st
import pandas as pd
from databricks import sql
from st_aggrid import AgGrid, GridOptionsBuilder, GridUpdateMode

# ====================================================================
# CONFIGURATION
# ====================================================================
warehouse_id = "f50df4c3b0b8cb91"
DATABRICKS_SERVER = "adb-4151713458336319.19.azuredatabricks.net"
DATABRICKS_TOKEN = "dapi97bfcf4f2625d2d7d1c1982bcee6cf8d-3"

# ====================================================================
# HELPER FUNCTIONS
# ====================================================================
@st.cache_data
def sqlQuery(query: str) -> pd.DataFrame:
    with sql.connect(
        server_hostname=DATABRICKS_SERVER,
        http_path=f"/sql/1.0/warehouses/{warehouse_id}",
        access_token=DATABRICKS_TOKEN
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute(query)
            return cursor.fetchall_arrow().to_pandas()

# ====================================================================
# QUERY MENU
# ====================================================================
queries = [
    "001-CG1594 - WIP TAB",
    "002-CG1594 - PUBLISHED TAB",
    "2025 Workload",
    "Add Duplicate GMW to WIP",
    "Additional Documents",
    "All Active Standards",
    "Assign Multiple GMWs",
    "Body",
    "Body Changes",
    "CSV01 for Accuris - EXTERNAL RESTRICTED",
    "CSV02 for Accuris - HIGHLY RESTRICTED",
    "CSV03 for Accuris - EXTERNAL",
    "CSV04 for CG2569 - All",
    "CSV05 for CG2569 - Eng Stds Pub",
    "DNG",
    "Editables",
    "Fix Ownerships",
    "ILS: 001-WIP",
    "ILS: 002-OOPS - Ready to Publish",
    "ILS: 002-Ready to Publish",
    "ILS: 003-Submitted to Publisher",
    "ILS: 004-Published",
    "ILS: Batch Sheet - Additional Documents Folder",
    "ILS: Batch Sheet - ES Published Folder",
    "RECONCILE: Mark Published",
    "RECONCILE: Published Documents",
    "RECONCILE: TCIMM Notification",
    "Regionals",
    "Send to ILM folders-Remove from All Data",
    "SPCs",
    "Special Collection Honda Electrification (BEV)",
    "Special Collections - Monthly Publishing",
    "Update from CSV",
    "Year End Cleanup - Remove Duplicates",
    "Year End Cleanup - Remove Published",
    "Yearly ILM Review-Inactive",
    "Yearly ILM Review-LU/SUPER",
    "z0-Judy Tracking for Analysts - Status Report",
    "z0-Judy's Nagging List",
    "z1-Judy's Tracking List-WIP"
]


st.sidebar.title("Queries")
selection = None
for q in queries:
    if st.sidebar.button(q):
        selection = q
        break

# ====================================================================
# DISPLAY DATA
# ====================================================================
if selection:
    st.write(f"**Selected Query:** {selection}")
    
    sql_map = {
    "001-CG1594 - WIP TAB": """SELECT 
    Record_ID, 
    WIP_Title, 
    Project, 
    Submit_Date, 
    Days_in_Process, 
    Key_Contact, 
    Analyst, 
    Action, 
    Local_Standards_Replaced, 
    Replaced_By, 
    Checked_for_Regulatory, 
    CG_Tracking_ID, 
    WIP_TAB, 
    PUBLISHED_TAB, 
    Ownership, 
    Final_Date, 
    ILS_Ready_to_Publish, 
    team_name_gdm, 
    Distribution_YYYYMM, 
    Distribution_YYYYMM_GDM, 
    Single_Point_Contact, 
    Num_Pages, 
    Team_Name, 
    Engineering_Standards_Status_GDM, 
    History, 
    Comments_to_Retain, 
    ILS_Comments, 
    ILS_Status, 
    Whats_the_Plan, 
    ILS_WIP, 
    Distribution_Type_Permitted_GDM, 
    Information_Security_Classification_GDM, 
    wl_2023_transfers, 
    Judy_Tracking_for_Analyst, 
    show_on_judy_tracking, 
    workload_2025_comments,
    KC_GMIN, 
    KC_Email
FROM maxis_sandbox.engineering_standards.all_data_cleaned
WHERE WIP_TAB = True
ORDER BY Record_ID, WIP_Title
""",
    "002-CG1594 - PUBLISHED TAB": """select record_id,
wip_title,
project,
submit_date,
days_in_process,
key_contact,
analyst,
action,
local_standards_replaced,
replaced_by,
checked_for_regulatory,
distribution_year,
final_disposition_action,
final_date,
ils_published,
duplicates_for_published_tab_only,
process_step,
current_step_date,
num_pages,
ownership,
location,
days_in_step,
distribution_yyyymm_gdm,
wl_2023_transfers,
workload_2024_comments
from maxis_sandbox.engineering_standards.all_data_cleaned
where published_tab = true or duplicates_for_published_tab_only = true
order by record_id,final_date""",
    "2025 Workload": """select 
workload_2025_comments,
regional_elimination_planned_year,
team_name,
ownership,
single_point_contact,
key_contact,
date_editable_requested,
requestor_of_editable,
record_id,
hyperlink_latest_version_gdm,
name_gdm,
title_gdm,
engineering_standards_status_gdm,
native_language_title_gdm,
distribution_yyyymm_gdm,
distribution_type_permitted_gdm,
information_security_classification_gdm,
record_subtype_gdm,
standards_validation_area_gdm,
team_name_gdm,
stakeholders_gdm,
authors_gdm,
vpps_via_version,
vpps_via_level_1_gdm,
vpps_via_level_2_gdm,
vpps_via_level_3_gdm,
vpps_via_level_4_gdm,
standards_category_gdm,
standards_subcategory_gdm,
version_gdm,
user_comments_gdm,
description_gdm,
keyword_gdm,
alias_gdm,
region_gdm,
language_gdm,
electronic_collection_gdm,
regulatory_date_gdm,
regulatory_standards_gdm,
record_id_issue_date_gdm,
owner_gdm,
content_date_gdm,
modifier_gdm,
modified_gdm,
source_system_gdm,
source_sys_load_date_gdm,
modifier_2_gdm,
object_id_gdm,
record_type_gdm,
global_process_area_gdm,
rim_category_gdm,
applicable_business_processes_gdm,
folder_gdm,
wip_tab,
published_tab,
analyst,
action,
project,
submit_date,
final_disposition_action,
final_date,
once,
wip_title,
do_not_include,
kc_gmin,
kc_email,
ils_ready_to_publish
from maxis_sandbox.engineering_standards.all_data_cleaned
WHERE Do_not_include = False AND Duplicates_for_Published_Tab_Only = False
ORDER BY Record_ID""",
    "Add Duplicate GMW to WIP": """SELECT 
record_id,
comments_to_retain,
wip_tab,
published_tab,
duplicates_for_published_tab_only,
analyst,
last_analyst,
total_num_pgs_pubd,
wip_title,
team_name,
single_point_contact,
key_contact,
ownership,
project,
action,
local_standards_replaced,
submit_date,
requestor_of_editable,
date_editable_requested,
record_id_gdm,
hyperlink_latest_version_gdm,
name_gdm,
title_gdm,
engineering_standards_status_gdm,
native_language_title_gdm,
distribution_yyyymm_gdm,
distribution_type_permitted_gdm,
information_security_classification_gdm,
record_subtype_gdm,
standards_validation_area_gdm,
team_name_gdm,
stakeholders_gdm,
authors_gdm,
vpps_via_version,
vpps_via_level_1_gdm,
vpps_via_level_2_gdm,
vpps_via_level_3_gdm,
vpps_via_level_4_gdm,
standards_category_gdm,
standards_subcategory_gdm,
version_gdm,
user_comments_gdm,
description_gdm,
keyword_gdm,
alias_gdm,
region_gdm,
language_gdm,
electronic_collection_gdm,
regulatory_date_gdm,
regulatory_standards_gdm,
record_id_issue_date_gdm,
owner_gdm,
content_date_gdm,
modifier_gdm,
modified_gdm,
source_system_gdm,
source_sys_load_date_gdm,
modifier_2_gdm,
object_id_gdm,
record_type_gdm,
global_process_area_gdm,
rim_category_gdm,
applicable_business_processes_gdm,
folder_gdm,
distribution_year,
distribution_yyyymm,
team_name_on_cg746,
days_in_process,
checked_for_regulatory,
cg_tracking_id,
num_pages,
final_disposition_action,
final_date,
pending_gmw_for_cg,
process_step,
location,
current_step_date,
days_in_step,
history,
ils_wip,
ils_ready_to_publish,
ils_submitted_to_publisher,
ils_published,
ils_action,
action_2,
replaced_by,
ils_submit_date,
ils_status,
ils_comments,
priority,
project_998_list,
project_998_closed,
rep_998_comments,
rep_998_action,
rep_998_replaced_by,
regional_elimination_planned_year,
area_998,
update_csv,
temp_check_box,
confirmed_no_supplements,
materials_998s_2022,
whats_the_plan,
honda_autonomous_special_collection,
honda_autonomous_added,
honda_autonomous_confirmed,
honda_autonomous_most_current_version_approved,
honda_autonomous_audit_found,
honda_electrification_bev_special_collection,
honda_electrification_bev_added,
honda_electrification_bev_confirmed,
honda_electrification_bev_most_current_version_approved,
honda_electrification_bev_audit_found,
cruise_automation_special_collection,
cruise_added,
cruise_confirmed,
cruise_most_current_version_approved,
cruise_audit_found,
workload_2023_comments,
comments_cruise_automation_special_collection,
comments_honda_autonomous_special_collection,
comments_honda_electrification_bev_special_collection,
sco_message_20221202,
assign_2023,
etl,
next_follow_up,
honda_affordable_electric_vehicle_aev_special_collection,
honda_affordable_electric_vehicle_aev_added,
honda_affordable_electric_vehicle_aev_confirmed,
comments_honda_aev,
country,
referenced_records,
personal_information_included,
non_disclosure_agreement_applies,
export_control_number,
source_rec_id,
source_rec_info,
source_rec_url,
format,
follow_up_comments,
record_status,
wl_2023_transfers,
update_csv_2,
wl_2023_transfer_status,
record_id_ihs,
ihs_audit_comments,
show_on_judy_tracking,
judy_tracking_for_analyst,
analyst_tracking_for,
assign_2024,
do_not_include,
workload_2024_comments,
once,
powertrain_comments,
once_comments,
distribution_date,
workload_2025_comments
from maxis_sandbox.engineering_standards.all_data_cleaned
order by record_id

""",
    "Additional Documents": "SELECT * FROM table_additional_documents LIMIT 100",
    "All Active Standards": "SELECT * FROM table_all_active_standards LIMIT 100",
    "Assign Multiple GMWs": "SELECT * FROM table_assign_multiple_gmws LIMIT 100",
    "Body": "SELECT * FROM table_body LIMIT 100",
    "Body Changes": "SELECT * FROM table_body_changes LIMIT 100",
    "CSV01 for Accuris - EXTERNAL RESTRICTED": "SELECT * FROM table_csv01 LIMIT 100",
    "CSV02 for Accuris - HIGHLY RESTRICTED": "SELECT * FROM table_csv02 LIMIT 100",
    "CSV03 for Accuris - EXTERNAL": "SELECT * FROM table_csv03 LIMIT 100",
    "CSV04 for CG2569 - All": "SELECT * FROM table_csv04 LIMIT 100",
    "CSV05 for CG2569 - Eng Stds Pub": "SELECT * FROM table_csv05 LIMIT 100",
    "DNG": "SELECT * FROM table_dng LIMIT 100",
    "Editables": "SELECT * FROM table_editables LIMIT 100",
    "Fix Ownerships": "SELECT * FROM table_fix_ownerships LIMIT 100",
    "ILS: 001-WIP": "SELECT * FROM table_ils_001_wip LIMIT 100",
    "ILS: 002-OOPS - Ready to Publish": "SELECT * FROM table_ils_002_oops LIMIT 100",
    "ILS: 002-Ready to Publish": "SELECT * FROM table_ils_002_ready LIMIT 100",
    "ILS: 003-Submitted to Publisher": "SELECT * FROM table_ils_003_submitted LIMIT 100",
    "ILS: 004-Published": "SELECT * FROM table_ils_004_published LIMIT 100",
    "ILS: Batch Sheet - Additional Documents Folder": "SELECT * FROM table_ils_batch_additional LIMIT 100",
    "ILS: Batch Sheet - ES Published Folder": "SELECT * FROM table_ils_batch_es_published LIMIT 100",
    "RECONCILE: Mark Published": "SELECT * FROM table_reconcile_mark_published LIMIT 100",
    "RECONCILE: Published Documents": "SELECT * FROM table_reconcile_published LIMIT 100",
    "RECONCILE: TCIMM Notification": "SELECT * FROM table_reconcile_tcimm LIMIT 100",
    "Regionals": "SELECT * FROM table_regionals LIMIT 100",
    "Send to ILM folders-Remove from All Data": "SELECT * FROM table_send_to_ilm LIMIT 100",
    "SPCs": "SELECT * FROM table_spcs LIMIT 100",
    "Special Collection Honda Electrification (BEV)": "SELECT * FROM table_special_honda LIMIT 100",
    "Special Collections - Monthly Publishing": "SELECT * FROM table_special_monthly LIMIT 100",
    "Update from CSV": "SELECT * FROM table_update_csv LIMIT 100",
    "Year End Cleanup - Remove Duplicates": "SELECT * FROM table_year_end_duplicates LIMIT 100",
    "Year End Cleanup - Remove Published": "SELECT * FROM table_year_end_published LIMIT 100",
    "Yearly ILM Review-Inactive": "SELECT * FROM table_yearly_ilm_inactive LIMIT 100",
    "Yearly ILM Review-LU/SUPER": "SELECT * FROM table_yearly_ilm_lu_super LIMIT 100",
    "z0-Judy Tracking for Analysts - Status Report": "SELECT * FROM table_judy_tracking_status LIMIT 100",
    "z0-Judy's Nagging List": "SELECT * FROM table_judy_nagging LIMIT 100",
    "z1-Judy's Tracking List-WIP": "SELECT * FROM table_judy_tracking_wip LIMIT 100"
}

    
    query_string = sql_map.get(selection, f"SELECT * FROM {selection.replace(' ', '_')} LIMIT 100")
    df = sqlQuery(query_string)
    
    gb = GridOptionsBuilder.from_dataframe(df)
    gb.configure_pagination()
    gb.configure_default_column(editable=True)
    grid_options = gb.build()
    
    AgGrid(df, gridOptions=grid_options, update_mode=GridUpdateMode.NO_UPDATE)
